import { getCareersPage, getSiteSettings } from '@/lib/sanity'
import { mergeWithFallback } from '@/lib/fallback'
import { mapPageCta } from '@/lib/contentFallbacks'
import CareersClient from './CareersClient'

const fallbackData = {
  heroSubtitle: 'Careers',
  heroSubtitleColor: '#10b981',
  heroSubtitleSize: '14px',
  heroSubtitleBorderEnabled: false,
  heroSubtitleBorderColor: '#000000',
  heroSubtitleBorderWidth: '1px',
  heroSubtitleShadowColor: '',
  heroTitle: 'Join Our Team',
  heroTitleColor: '#ffffff',
  heroTitleSize: '72px',
  heroTitleBorderEnabled: false,
  heroTitleBorderColor: '#ffffff',
  heroTitleBorderWidth: '1px',
  heroTitleShadowColor: '',
  heroDescription: 'Atlas Fuel is powered by people who are passionate about excellence, innovation, and growth. We invest in our team with training, development, and opportunities to advance.',
  heroDescriptionColor: '#ffffff',
  heroDescriptionSize: '18px',
  heroDescriptionBorderEnabled: false,
  heroDescriptionBorderColor: '#ffffff',
  heroDescriptionBorderWidth: '1px',
  heroDescriptionShadowColor: '',
  heroImageUrl: '/images/work-with-us.jpg',
  heroCtaText: 'View Openings',
  heroCtaLink: '#openings',
  secondaryCtaText: 'About Us',
  secondaryCtaLink: '/about',
  stats: [
    {value: '300+', label: 'Jobs Created'},
    {value: '50+', label: 'Talent Rising'},
    {value: '100%', label: 'Australian Owned'},
    {value: '24/7', label: 'Support Culture'},
  ],
  whyWorkHeading: 'Why Work With Us',
  whyWorkHeadingColor: '#000000',
  whyWorkHeadingSize: '48px',
  whyWorkHeadingBorderEnabled: false,
  whyWorkHeadingBorderColor: '#000000',
  whyWorkHeadingBorderWidth: '1px',
  whyWorkHeadingShadowColor: '',
  whyWorkDescription: 'At Atlas Fuel, we believe our people are our greatest asset. Join a team that values growth, safety, and excellence.',
  whyWorkDescriptionColor: '#000000',
  whyWorkDescriptionSize: '18px',
  whyWorkDescriptionBorderEnabled: false,
  whyWorkDescriptionBorderColor: '#000000',
  whyWorkDescriptionBorderWidth: '1px',
  whyWorkDescriptionShadowColor: '',
  whyWorkEyebrow: 'Why Atlas Fuel',
  cultureHeading: 'Driven by People, Fueled by Purpose',
  cultureHeadingColor: '#000000',
  cultureHeadingSize: '48px',
  cultureHeadingBorderEnabled: false,
  cultureHeadingBorderColor: '#000000',
  cultureHeadingBorderWidth: '1px',
  cultureHeadingShadowColor: '',
  cultureDescription: 'At Atlas Fuel, we believe our people are our greatest asset. We foster a culture of respect, innovation, and continuous improvement. Every team member plays a vital role in our success.',
  cultureDescriptionColor: '#000000',
  cultureDescriptionSize: '18px',
  cultureDescriptionBorderEnabled: false,
  cultureDescriptionBorderColor: '#000000',
  cultureDescriptionBorderWidth: '1px',
  cultureDescriptionShadowColor: '',
  cultureEyebrow: 'Our Culture',
  values: ['Safety First', 'Customer Focus', 'Integrity', 'Teamwork', 'Innovation'],
  cultureCtaText: 'Learn More About Us',
  cultureCtaLink: '/about',
  openingsHeading: 'Current Openings',
  openingsHeadingColor: '#000000',
  openingsHeadingSize: '48px',
  openingsHeadingBorderEnabled: false,
  openingsHeadingBorderColor: '#000000',
  openingsHeadingBorderWidth: '1px',
  openingsHeadingShadowColor: '',
  openingsEyebrow: 'Opportunities',
  jobCtaText: 'Apply Now',
  jobCtaLink: '/contact',
  talentHeading: 'Talent Rising Program',
  talentHeadingColor: '#000000',
  talentHeadingSize: '48px',
  talentHeadingBorderEnabled: false,
  talentHeadingBorderColor: '#000000',
  talentHeadingBorderWidth: '1px',
  talentHeadingShadowColor: '',
  talentDescription: 'Our 50+ Talent Rising program trains and employs young people, giving them valuable skills and experience to build lasting careers in the fuel industry. We believe in investing in the next generation of industry leaders.',
  talentDescriptionColor: '#000000',
  talentDescriptionSize: '18px',
  talentDescriptionBorderEnabled: false,
  talentDescriptionBorderColor: '#000000',
  talentDescriptionBorderWidth: '1px',
  talentDescriptionShadowColor: '',
  talentEyebrow: 'Training Program',
  talentStatValue: '50+',
  talentStatLabel: 'Talent Rising',
  talentStatDescription: 'Young professionals trained annually through our program',
  talentFeatures: ['Comprehensive hands-on training', 'Mentorship from industry veterans', 'Nationally recognized certifications', 'Clear career progression paths', 'Competitive trainee salaries'],
  talentCtaText: 'Apply for Program',
  talentCtaLink: '/contact',
  teamGalleryHeading: 'Life at Atlas Fuel',
  teamGalleryHeadingColor: '#000000',
  teamGalleryHeadingSize: '48px',
  teamGalleryHeadingBorderEnabled: false,
  teamGalleryHeadingBorderColor: '#000000',
  teamGalleryHeadingBorderWidth: '1px',
  teamGalleryHeadingShadowColor: '',
  teamGalleryEyebrow: 'Our Team',
  officeHeading: 'Modern Work Environment',
  officeHeadingColor: '#000000',
  officeHeadingSize: '48px',
  officeHeadingBorderEnabled: false,
  officeHeadingBorderColor: '#000000',
  officeHeadingBorderWidth: '1px',
  officeHeadingShadowColor: '',
  officeDescription: 'Our offices are designed to foster collaboration, creativity, and productivity across all our locations.',
  officeDescriptionColor: '#000000',
  officeDescriptionSize: '18px',
  officeDescriptionBorderEnabled: false,
  officeDescriptionBorderColor: '#000000',
  officeDescriptionBorderWidth: '1px',
  officeDescriptionShadowColor: '',
  officeEyebrow: 'Our Offices',
  trainingHeading: 'Training & Development',
  trainingHeadingColor: '#000000',
  trainingHeadingSize: '48px',
  trainingHeadingBorderEnabled: false,
  trainingHeadingBorderColor: '#000000',
  trainingHeadingBorderWidth: '1px',
  trainingHeadingShadowColor: '',
  trainingDescription: 'Comprehensive training programs that equip our team with the skills and certifications needed for success.',
  trainingDescriptionColor: '#000000',
  trainingDescriptionSize: '18px',
  trainingDescriptionBorderEnabled: false,
  trainingDescriptionBorderColor: '#000000',
  trainingDescriptionBorderWidth: '1px',
  trainingDescriptionShadowColor: '',
  trainingEyebrow: 'Training',
  eventsHeading: 'Team Events & Activities',
  eventsHeadingColor: '#000000',
  eventsHeadingSize: '48px',
  eventsHeadingBorderEnabled: false,
  eventsHeadingBorderColor: '#000000',
  eventsHeadingBorderWidth: '1px',
  eventsHeadingShadowColor: '',
  eventsDescription: 'Building strong relationships through team building, community involvement, and celebration of achievements.',
  eventsDescriptionColor: '#000000',
  eventsDescriptionSize: '18px',
  eventsDescriptionBorderEnabled: false,
  eventsDescriptionBorderColor: '#000000',
  eventsDescriptionBorderWidth: '1px',
  eventsDescriptionShadowColor: '',
  eventsEyebrow: 'Community',
  excellenceTagline: 'Driven by People, Fueled by Purpose',
  excellenceTaglineColor: '#000000',
  excellenceTaglineSize: '24px',
  excellenceTaglineBorderEnabled: false,
  excellenceTaglineBorderColor: '#000000',
  excellenceTaglineBorderWidth: '1px',
  excellenceTaglineShadowColor: '',
  excellenceContent: 'Atlas Fuel\'s team is dedicated to delivering excellence, combining expertise with a deep understanding of our clients\' needs. Our people prioritize reliability, safety, and customer satisfaction, ensuring seamless service at every step.',
  excellenceContentColor: '#000000',
  excellenceContentSize: '18px',
  excellenceContentBorderEnabled: false,
  excellenceContentBorderColor: '#000000',
  excellenceContentBorderWidth: '1px',
  excellenceContentShadowColor: '',
  excellenceCtaText: 'View Openings',
  excellenceCtaLink: '#openings',
  excellenceEyebrow: 'Our Philosophy',
  applicationEyebrow: 'Apply Now',
  applicationHeading: 'Join Our Team',
  applicationDescription: "We're looking for talented individuals who are passionate about making a difference.",
  applicationButtonText: 'Submit Application',
  applicationFields: [
    {name: 'fullName', label: 'Full Name', type: 'text', placeholder: 'Your full name'},
    {name: 'email', label: 'Email Address', type: 'email', placeholder: 'your@email.com'},
    {name: 'phone', label: 'Phone Number', type: 'tel', placeholder: 'Your phone number'},
    {name: 'position', label: 'Position Applied For', type: 'text', placeholder: "Position you're applying for"},
    {name: 'coverLetter', label: 'Cover Letter', type: 'textarea', placeholder: "Tell us about yourself and why you'd like to join Atlas Fuel", fullWidth: true},
  ],
}

const fallbackSiteSettings = {
  ctaBannerHeading: 'Ready to Join Our Team?',
  ctaBannerText: 'Explore our current openings and discover how you can build a rewarding career with Atlas Fuel.',
  ctaBannerButtonText: 'View Openings',
  ctaBannerButtonLink: '#openings',
}

export default async function CareersPage() {
  const [sanity, siteSettings] = await Promise.all([
    getCareersPage().catch(() => null),
    getSiteSettings().catch(() => null),
  ])

  const data = mergeWithFallback(fallbackData, sanity)
  const settings = mapPageCta(sanity, siteSettings, fallbackSiteSettings)

  return (
    <>
      <CareersClient data={data} siteSettings={settings} />
    </>
  )
}
